CONFIG_ID=0
CONFIG_POWER=1
CONFIG_HEALTH=2
CONFIG_SHIELD=3
CONFIG_RESPAWN_DELAY=4
CONFIG_FIRE_THRESHOLD=5
CONFIG_FIRE_CHEATING=6
CONFIG_FIRE_HOLDOFF=7
CONFIG_DEATH_PERIOD=8

CONFIG_ID_INIT_FLAG = 1<<9

FLASH_CONFIG = 0x7F0
FLASH_HITLIST = 0x7E0

ID_UNINIT = 0x80
